#!/usr/bin/env python3
"""Emitters - one View, many surfaces.

Rendering is deliberately separate from the lenses that produce a View (lenses.py). A lens
decides WHAT is true; an emitter decides how it is shown. That split is what lets the same
projection appear as a markdown table in a note, a mermaid graph in Obsidian or on GitHub,
JSON for any custom viewer, and an Obsidian `.base` file for people who live in Bases.

The `.base` target is the interesting one. A Base can filter, sort and group STORED
frontmatter; it cannot compute a ranking over note state. So the emitter renders the closest
expressible approximation and SAYS SO in the file it writes, rather than pretending the
formats are equivalent. That is the whole thesis in one function: the competitor's format is
one output of this algebra, not a thing to copy.

Stdlib only. Every function is pure: View in, string out.
"""


def _cell(v) -> str:
    if v is None:
        return ""
    if isinstance(v, bool):
        return "yes" if v else ""
    if isinstance(v, float):
        s = f"{v:.3f}".rstrip("0").rstrip(".")
    else:
        s = str(v)
    # A '|' or newline inside a cell silently shifts every later column of the table
    # (review 2026-08: LLM-extracted titles are free text - 'use torch.load | not .cuda()'
    # rendered confidence under the wrong header). Escape, never truncate.
    return s.replace("\r", " ").replace("\n", " ").replace("|", "\\|")


def _mlabel(s) -> str:
    """Mermaid node/edge label text: a double quote closes the [\"...\"] wrapper and breaks
    the whole diagram (raw user input reaches here via the causal lens root entity)."""
    return str(s).replace('"', "'").replace("|", "/")


def to_markdown(v) -> str:
    """A markdown table (or an edge list for a graph view). Renders in any note, any agent
    transcript, any README - the lowest-common-denominator surface."""
    out = [f"### {v.title}"] if v.title else []
    if v.meta.get("note"):
        out.append(f"_{v.meta['note']}_")
    out.append("")
    if not v.rows:
        out.append("_(nothing to show)_")
        return "\n".join(out)
    cols = v.columns or list(v.rows[0].keys())
    out.append("| " + " | ".join(cols) + " |")
    out.append("|" + "|".join("---" for _ in cols) + "|")
    for r in v.rows:
        out.append("| " + " | ".join(_cell(r.get(c)) for c in cols) + " |")
    if v.meta.get("failure_modes"):
        out += ["", "**Known failure modes:**"] + [f"- {f}" for f in v.meta["failure_modes"]]
    return "\n".join(out)


def to_mermaid(v) -> str:
    """A mermaid graph - renders natively in Obsidian and in a GitHub markdown block, so a
    graph view needs no tool installed and no image committed."""
    if not v.edges:
        return "```mermaid\ngraph LR\n  empty[no edges]\n```"
    nodes, ids = [], {}
    for e in v.edges:
        for n in (e["source"], e["target"]):
            if n not in ids:
                ids[n] = f"n{len(ids)}"
                nodes.append(n)
    out = ["```mermaid", "graph LR"]
    out += [f'  {ids[n]}["{_mlabel(n)}"]' for n in nodes]
    out += [f'  {ids[e["source"]]} -->|{_mlabel(e["rel"])}| {ids[e["target"]]}'
            for e in v.edges]
    out.append("```")
    return "\n".join(out)


def to_json(v) -> str:
    import json
    return json.dumps({"kind": v.kind, "title": v.title, "columns": v.columns,
                       "rows": v.rows, "edges": v.edges, "meta": v.meta},
                      ensure_ascii=False, indent=1)


# Frontmatter fields an Obsidian Base can actually address. A view column outside this set
# has no stored counterpart, so the Base cannot show it - the emitter drops it and says why.
_BASE_FIELDS = {"confidence", "recurrence", "salience", "project", "type", "status",
                "resolved", "date", "tags", "superseded_by"}


def to_base(v) -> str:
    """An Obsidian `.base` file: the same projection, expressed within what Bases can do.

    Honest by construction. Computed columns (a risk score, a hop count) have no frontmatter
    to bind to, so they are dropped and listed in a header comment together with the filter
    this view is approximating. A reader opening the Base in Obsidian learns exactly which
    part of the lens survived the translation."""
    cols = v.columns or (list(v.rows[0].keys()) if v.rows else [])
    keep = [c for c in cols if c in _BASE_FIELDS]
    lost = [c for c in cols if c not in _BASE_FIELDS]
    out = [f"# {v.title} - generated by nevertwice (lenses.py)"]
    if v.meta.get("base_note"):
        out.append(f"# {v.meta['base_note']}")
    if lost:
        out.append(f"# Not expressible as a Base column: {', '.join(lost)}")
    out.append("filters:")
    out.append("  and:")
    out.append('    - file.ext == "md"')
    if v.meta.get("base_filter"):
        out.append(f'    - {v.meta["base_filter"]}')
    # A project-scoped lens must emit a project-scoped Base: `project` IS a stored field,
    # so dropping the scope was a silent loss the honesty header never disclosed (review
    # 2026-08: a --project frontier rendered every project's low-confidence notes).
    if v.meta.get("project"):
        out.append(f'    - project == "{v.meta["project"]}"')
    out.append("properties:")
    out.append("  file.name:")
    out.append("    displayName: Note")
    for c in keep:
        out.append(f"  {c}:")
        out.append(f"    displayName: {c.replace('_', ' ').title()}")
    out.append("views:")
    out.append("  - type: table")
    out.append(f"    name: {v.title}")
    out.append("    order:")
    out.append("      - file.name")
    for c in keep:
        out.append(f"      - {c}")
    # Sort on the field that best stands in for the lens's own ordering (the lens names it;
    # otherwise fall back to the first usable column). Without this the Base sorts by whatever
    # happened to come first and loses the one thing the approximation was for.
    sort_on = v.meta.get("base_sort") if v.meta.get("base_sort") in keep else (keep[0] if keep else "")
    if sort_on:
        out.append("    sort:")
        out.append(f"      - property: {sort_on}")
        out.append(f"        direction: {v.meta.get('base_sort_dir', 'ASC')}")
    return "\n".join(out)


EMITTERS = {"markdown": to_markdown, "md": to_markdown, "mermaid": to_mermaid,
            "json": to_json, "base": to_base}


def emit(v, fmt: str = "markdown") -> str:
    """Render `v` in `fmt`. Unknown formats fall back to markdown rather than raise: an
    emitter is a display choice, and a typo should not lose the answer. For the same reason
    a mermaid request against a TABLE view (no edges by construction) renders markdown -
    the empty-graph placeholder would silently discard every ranked row (review 2026-08)."""
    f = (fmt or "").lower()
    if f == "mermaid" and getattr(v, "kind", "") != "graph":
        f = "markdown"
    return EMITTERS.get(f, to_markdown)(v)
