#!/usr/bin/env python3
"""One visual system, and every figure says where it came from.

Eleven benches each called `fig.savefig(path, dpi=130)` with default Matplotlib styling. That
is four separate problems, three of which a reader can see:

* the tab10 default is not colourblind-safe, and several charts carried a pass/fail meaning in
  green against red alone;
* 130 dpi raster only - fine on the screen it was made on, blurred anywhere else, and
  unusable in print;
* no provenance on the image itself, so a chart that travelled past its page arrived with no
  sample size, no dataset, no model and no command;
* and diagrams drawn by hand, which nobody can re-check against what the system actually does.

So the rules here are: figures go through `research/_figstyle.py`, which refuses to save one
without an evidence line and writes SVG beside a 2x PNG; diagrams are generated by
`tools/make_diagrams.py` from a description in that file; and every image a tracked document
shows carries alt text that describes it rather than naming its file.
"""
from __future__ import annotations

import re
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))

import _env_guard  # noqa: F401, E402 - must run before any project import

RESEARCH = ROOT / "research"
DIAGRAMS = ROOT / "tools" / "make_diagrams.py"
SVGS = (ROOT / "docs" / "architecture.svg", ROOT / "docs" / "never-twice.svg")

# WCAG AA for body text. The palette is checked against the paper it is drawn on.
MIN_CONTRAST = 4.5
# An alt text shorter than this is a label, not a description of a chart.
MIN_ALT = 60

SAVEFIG = re.compile(r"^(?!\s*#).*\b(?:fig|plt|figure)\.savefig\s*\(", re.M)
IMG_TAG = re.compile(r'<img\s+[^>]*>', re.I)
MD_IMAGE = re.compile(r'!\[([^\]]*)\]\(([^)\s]+)')

# Vendored third-party corpora and GitHub's own surfaces are not this project's visuals.
SKIP_DOC_PREFIXES = ("research/embed_universal/", ".github/")

PASSED = 0
FAILED = 0


def check(name: str, condition: bool, detail: str = "") -> None:
    global PASSED, FAILED
    suffix = f"  [{detail}]" if detail and not condition else ""
    print(("  ok   " if condition else "  FAIL ") + name + suffix)
    PASSED += int(condition)
    FAILED += int(not condition)


def tracked(*patterns: str) -> list:
    out = subprocess.run(["git", "ls-files", *patterns], cwd=ROOT,
                         capture_output=True, text=True, timeout=60)
    if out.returncode != 0:
        return []
    return sorted(p for p in out.stdout.split()
                  if not p.startswith(SKIP_DOC_PREFIXES))


def luminance(hex_colour: str) -> float:
    r, g, b = (int(hex_colour[i:i + 2], 16) / 255 for i in (1, 3, 5))
    lin = [(c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4) for c in (r, g, b)]
    return 0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2]


def contrast(fg: str, bg: str) -> float:
    a, b = luminance(fg), luminance(bg)
    hi, lo = max(a, b), min(a, b)
    return (hi + 0.05) / (lo + 0.05)


def figure_scripts() -> list:
    """Every bench that draws, excluding the shared helper that draws for them."""
    return [p for p in sorted(RESEARCH.glob("*.py"))
            if p.name != "_figstyle.py"
            and "matplotlib" in p.read_text(encoding="utf-8", errors="replace")]


def test_no_figure_escapes_the_shared_style() -> None:
    print("\n- every figure is written by research/_figstyle.py -")
    scripts = figure_scripts()
    check("figure scripts were found", len(scripts) >= 10, str(len(scripts)))

    direct, unstyled = [], []
    for path in scripts:
        text = path.read_text(encoding="utf-8", errors="replace")
        if SAVEFIG.search(text):
            direct.append(path.name)
        if "_figstyle.save(" in text and "_figstyle.apply()" not in text:
            unstyled.append(path.name)
    check("no script calls savefig directly", not direct, ", ".join(direct))
    check("every script that saves also applies the style", not unstyled,
          ", ".join(unstyled))

    # The one place savefig is allowed, and the guard that makes the footer mandatory.
    style = (RESEARCH / "_figstyle.py").read_text(encoding="utf-8")
    check("the shared helper is the only caller of savefig", "fig.savefig(target" in style)
    check("negative results are carried by a hatch as well as a colour",
          "NEGATIVE_HATCH" in style)

    # Exercised, not grepped: a first pass asserted the words "raise ValueError" were present,
    # and a mutant that disabled the branch while leaving the words in place walked straight
    # through it. Call save() and see what happens instead.
    sys.path.insert(0, str(RESEARCH))
    import matplotlib                                   # noqa: PLC0415 - after the guard
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt                     # noqa: PLC0415
    import _figstyle                                    # noqa: PLC0415

    with tempfile.TemporaryDirectory(prefix="nevertwice_fig_") as tmp:
        target = Path(tmp) / "probe.png"
        for label, kwargs in (("neither claim nor evidence", {}),
                              ("both claim and evidence",
                               {"claim": "qa.oracle.answer_accuracy", "evidence": "x" * 40})):
            fig = plt.figure()
            try:
                _figstyle.save(fig, target, **kwargs)
                check(f"save() refuses {label}", False, "it wrote the figure anyway")
            except ValueError:
                check(f"save() refuses {label}", True)
            finally:
                plt.close(fig)
        check("nothing was written by a refused save", not list(Path(tmp).iterdir()),
              ", ".join(p.name for p in Path(tmp).iterdir()))

        fig = plt.figure()
        written = _figstyle.save(fig, target, evidence="n=1 · a written provenance line")
        plt.close(fig)
        check("save() writes an SVG and a PNG when it has provenance",
              sorted(p.suffix for p in written) == [".png", ".svg"],
              str([p.name for p in written]))


def test_every_published_figure_has_a_vector_twin_and_a_footer() -> None:
    print("\n- SVG beside every PNG, and an evidence line inside it -")
    # longitudinal_bench.png is the one figure not re-rendered through the helper. Its
    # `--save` recomputes the study before it plots, and the recomputation does not reproduce
    # the committed numbers (r@1 0.766 -> 0.760 on an identical seed), so re-rendering it here
    # would have quietly replaced a published result during a styling task. Recorded as a
    # reproducibility defect rather than papered over; this exclusion goes when it is fixed.
    NOT_YET = {"longitudinal_bench.png"}
    pngs = [ROOT / p for p in tracked("research/*.png")
            if Path(p).name not in NOT_YET]
    check("research figures are tracked", len(pngs) >= 8, str(len(pngs)))

    missing, thin = [], []
    for png in pngs:
        svg = png.with_suffix(".svg")
        if not svg.is_file():
            missing.append(png.name)
            continue
        body = svg.read_text(encoding="utf-8", errors="replace")
        # The footer is drawn as text into the figure, so it is in the vector output.
        if not re.search(r"(reproduce:|python research/|commit [0-9a-f]{7})", body):
            thin.append(svg.name)
    check("every figure has an SVG twin", not missing, ", ".join(missing[:5]))
    check("every SVG carries its evidence line", not thin, ", ".join(thin[:5]))

    # 2x: the helper's default dpi, asserted where it is declared rather than by
    # measuring pixels, which would make the test depend on each figure's inch size.
    style = (RESEARCH / "_figstyle.py").read_text(encoding="utf-8")
    check("PNG output is 2x", "dpi: int = 260" in style)


def test_the_diagrams_match_their_description() -> None:
    print("\n- the diagrams are generated, not drawn -")
    proc = subprocess.run([sys.executable, str(DIAGRAMS)], cwd=ROOT, capture_output=True,
                          text=True, timeout=300, encoding="utf-8", errors="replace")
    check("tools/make_diagrams.py reports both current", proc.returncode == 0,
          (proc.stdout + proc.stderr).strip()[:300])

    for svg in SVGS:
        name = svg.name
        check(f"{name} exists", svg.is_file())
        if not svg.is_file():
            continue
        body = svg.read_text(encoding="utf-8")
        check(f"{name} has a <title>", "<title" in body)
        desc = re.search(r"<desc[^>]*>(.*?)</desc>", body, re.S)
        check(f"{name} has a <desc> that describes it",
              desc is not None and len(desc.group(1)) > 200,
              f"{len(desc.group(1)) if desc else 0} chars")
        check(f"{name} declares role=img", 'role="img"' in body)
        check(f"{name} paints its own background", 'fill="#FFFFFF"' in body)

    arch = SVGS[0].read_text(encoding="utf-8")
    for required in ("WRITE TIME", "READ TIME", "0 tokens", "local", "intervention point"):
        check(f"the architecture names {required!r}", required in arch)

    seq = SVGS[1].read_text(encoding="utf-8")
    check("the sequence has four frames",
          len(re.findall(r'font-weight="700"\s+text-anchor="middle"', seq)) == 4,
          str(len(re.findall(r'font-weight="700"\s+text-anchor="middle"', seq))))
    check("the sequence names the command it depicts", "guard_demo.py --check" in seq)


def test_the_palette_is_readable() -> None:
    print("\n- contrast and colour-independence -")
    sys.path.insert(0, str(RESEARCH))
    import _figstyle                                    # noqa: PLC0415 - after the guard

    for name in ("INK", "MUTED"):
        ratio = contrast(getattr(_figstyle, name), _figstyle.PAPER)
        check(f"{name} on paper is at least {MIN_CONTRAST}:1", ratio >= MIN_CONTRAST,
              f"{ratio:.1f}:1")

    # Okabe-Ito is the point: a palette chosen for colour vision deficiency, not for looks.
    check("the palette is Okabe-Ito", _figstyle.PALETTE[0] == "#0072B2"
          and "#E69F00" in _figstyle.PALETTE and "#009E73" in _figstyle.PALETTE)
    check("the palette has at least six distinct colours",
          len(set(_figstyle.PALETTE)) >= 6)
    check("status colours are not a red/green pair",
          _figstyle.POSITIVE != "#008000" and _figstyle.NEGATIVE != "#FF0000"
          and _figstyle.POSITIVE == _figstyle.PALETTE[0])

    # The literals the old figures used. `color="green"` against `color="red"` is the exact
    # encoding that disappears for a colourblind reader.
    offenders = []
    for path in figure_scripts():
        text = path.read_text(encoding="utf-8", errors="replace")
        for bad in ('color="red"', "color='red'", 'color="green"', "color='green'",
                    'color="lime"', '"#2ea043"', '"#ff0000"'):
            if bad in text:
                offenders.append(f"{path.name}: {bad}")
    check("no figure hardcodes a red or green literal", not offenders,
          ", ".join(offenders[:4]))


def test_every_image_in_a_tracked_document_has_alt_text() -> None:
    print("\n- alt text everywhere, describing rather than naming -")
    missing, weak = [], []
    for rel in tracked("*.md"):
        text = (ROOT / rel).read_text(encoding="utf-8", errors="replace")
        for tag in IMG_TAG.findall(text):
            alt = re.search(r'alt="([^"]*)"', tag)
            src = re.search(r'src="([^"]*)"', tag)
            where = f"{rel}:{(src.group(1) if src else '?').split('/')[-1]}"
            if alt is None or not alt.group(1).strip():
                missing.append(where)
            elif len(alt.group(1)) < MIN_ALT or alt.group(1).lower().endswith(
                    (".png", ".svg", ".gif")):
                weak.append(f"{where} ({len(alt.group(1)) if alt else 0} chars)")
        for alt, src in MD_IMAGE.findall(text):
            if src.startswith(("http://", "https://")):
                continue                     # badges and remote assets carry their own label
            where = f"{rel}:{src.split('/')[-1]}"
            if not alt.strip():
                missing.append(where)
            elif len(alt) < MIN_ALT:
                weak.append(f"{where} ({len(alt)} chars)")
    check("every local image has alt text", not missing, ", ".join(missing[:5]))
    check(f"every alt text describes the image (>= {MIN_ALT} chars)", not weak,
          ", ".join(weak[:5]))


if __name__ == "__main__":
    for _name, _fn in sorted(globals().items()):
        if _name.startswith("test_") and callable(_fn):
            try:
                _fn()
            except Exception as exc:            # noqa: BLE001 - report, keep going
                FAILED += 1
                print(f"  ERR  {_name}: {type(exc).__name__}: {exc}")
    print(f"\nvisual system: {PASSED} passed, {FAILED} failed")
    raise SystemExit(1 if FAILED else 0)
