#!/usr/bin/env python3
"""The evidence contract: no public number without traceable evidence.

`research/evidence_manifest.json` is the register. This suite enforces three things:

1. **Schema** - every claim carries the fields that make it checkable, and every
   dataset/environment reference resolves.
2. **Agreement with the raw results** - a claim that points into a committed result
   file must equal what that file actually says. Transcription drift dies here.
3. **Coverage** - every number printed in the documents the manifest claims to cover
   resolves to a claim, a quoted third-party citation, a declared non-metric, or a
   recorded drift entry. An unaccounted number is a claim with no evidence.
4. **Governance** - every tracked `.md` is registered as governed, exempt with a
   reason, or backlog with a budget that may only be lowered. A new document cannot
   quietly start publishing unevidenced numbers, and the unregistered surface can
   only shrink. Numbers inside a generated region do not count against a budget:
   they come from committed data through a tool whose own check runs in CI.

The tables inside the governed documents are generated by `tools/render_claims.py`,
and this suite runs it in check mode - so a hand-edited table fails here.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))

import _env_guard  # noqa: F401, E402 - must run before any project import

MANIFEST_PATH = ROOT / "research" / "evidence_manifest.json"

PASSED = 0
FAILED = 0


def check(name: str, condition: bool, detail: str = "") -> None:
    global PASSED, FAILED
    suffix = f"  [{detail}]" if detail and not condition else ""
    print(("  ok   " if condition else "  FAIL ") + name + suffix)
    PASSED += int(condition)
    FAILED += int(not condition)


MANIFEST = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))

REQUIRED = ("id", "statement", "value", "printed", "unit", "dataset", "environment",
            "n", "command", "raw", "pointer", "commit", "ci", "cited_in")

# Fenced blocks are shell commands and illustrative terminal output, not measurements.
FENCE = re.compile(r"^```.*?^```", re.S | re.M)
NUMBER = re.compile(r"\d+(?:,\d{3})*(?:\.\d+)?")
# A block emitted by tools/render_claims.py or tools/comparison_snapshot.py.
GENERATED_REGION = re.compile(
    r"<!-- (claims|comparison):([\w-]+) -->.*?<!-- /\1:\2 -->", re.S)


def resolve(data, pointer: str):
    """Walk a dotted pointer with [index] segments, e.g. `a.b[2].c`."""
    node = data
    for part in pointer.split("."):
        while part.endswith("]"):
            part, _, idx = part[:-1].rpartition("[")
            if part:
                node = node[part]
            node = node[int(idx)]
            part = ""
        if part:
            node = node[part]
    return node


def test_schema_is_complete() -> None:
    print("\n- manifest schema -")
    check("schema_version is present", MANIFEST.get("schema_version") == 1)
    claims = MANIFEST["claims"]
    check("the manifest carries claims", len(claims) > 50, str(len(claims)))

    missing = [c.get("id", "?") for c in claims
               if any(f not in c for f in REQUIRED)]
    check("every claim carries the required fields", not missing,
          ", ".join(missing[:5]))

    ids = [c["id"] for c in claims]
    check("claim ids are unique", len(ids) == len(set(ids)),
          ", ".join(sorted({i for i in ids if ids.count(i) > 1})))

    bad_printed = [c["id"] for c in claims
                   if not c["printed"] or not all(isinstance(p, str) and p.strip()
                                                  for p in c["printed"])]
    check("every claim declares how it is printed", not bad_printed,
          ", ".join(bad_printed[:5]))

    unknown_ds = sorted({c["dataset"] for c in claims
                         if c["dataset"] and c["dataset"] not in MANIFEST["datasets"]})
    check("every dataset reference resolves", not unknown_ds, ", ".join(unknown_ds))

    unknown_env = sorted({c["environment"] for c in claims
                          if c["environment"]
                          and c["environment"] not in MANIFEST["environments"]})
    check("every environment reference resolves", not unknown_env,
          ", ".join(unknown_env))

    unscoped = sorted({d for c in claims for d in c["cited_in"]
                       if d not in MANIFEST["scope"]["docs"]})
    check("claims are only cited in documents the manifest covers", not unscoped,
          ", ".join(unscoped))


def test_untraceable_claims_say_so() -> None:
    print("\n- a claim with no raw file must admit it -")
    silent = [c["id"] for c in MANIFEST["claims"]
              if not c["raw"] and not c.get("raw_gap")]
    check("no claim lacks both a raw file and a stated reason", not silent,
          ", ".join(silent[:5]))

    derived = [c["id"] for c in MANIFEST["claims"]
               if c["raw"] and not c["pointer"] and not c.get("derivation")]
    check("a claim with a raw file but no pointer explains its derivation",
          not derived, ", ".join(derived[:5]))

    gaps = [c["id"] for c in MANIFEST["claims"] if c.get("raw_gap")]
    print(f"       ({len(gaps)} of {len(MANIFEST['claims'])} claims have no committed "
          f"raw artifact - each states why)")


def test_pointers_match_the_raw_results() -> None:
    print("\n- every pointer equals what the raw file says -")
    cache: dict[str, object] = {}
    mismatched: list[str] = []
    unreadable: list[str] = []
    checked = 0

    for c in MANIFEST["claims"]:
        if not c["raw"] or not c["pointer"]:
            continue
        path = ROOT / c["raw"]
        if c["raw"] not in cache:
            try:
                cache[c["raw"]] = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, ValueError) as exc:
                cache[c["raw"]] = exc
        data = cache[c["raw"]]
        if isinstance(data, Exception):
            unreadable.append(f"{c['id']} -> {c['raw']}")
            continue
        try:
            actual = resolve(data, c["pointer"])
        except (KeyError, IndexError, TypeError):
            unreadable.append(f"{c['id']} -> {c['raw']}:{c['pointer']}")
            continue
        checked += 1
        if isinstance(actual, float) or isinstance(c["value"], float):
            same = abs(float(actual) - float(c["value"])) < 1e-9
        else:
            same = actual == c["value"]
        if not same:
            mismatched.append(f"{c['id']}: manifest {c['value']!r} vs raw {actual!r}")

    check("every raw pointer resolves", not unreadable, "; ".join(unreadable[:4]))
    check(f"every one of the {checked} pointed claims matches its raw result",
          not mismatched, "; ".join(mismatched[:4]))


def test_confidence_intervals_are_sane() -> None:
    print("\n- declared intervals bracket their value -")
    broken = []
    for c in MANIFEST["claims"]:
        ci = c.get("ci")
        if not ci:
            continue
        if not (ci["low"] <= float(c["value"]) <= ci["high"]):
            broken.append(f"{c['id']}: {ci['low']}..{ci['high']} excludes {c['value']}")
    check("every interval contains its point estimate", not broken,
          "; ".join(broken[:4]))

    silent = [c["id"] for c in MANIFEST["claims"]
              if not c.get("ci") and not c.get("ci_note") and c["n"]
              and isinstance(c["n"], int) and c["unit"].startswith(("recall", "accuracy"))]
    check("a proportion with a sample size has an interval or a stated reason",
          not silent, ", ".join(silent[:5]))


def _accounted_forms() -> tuple[set[str], list[tuple]]:
    forms: set[str] = set()
    for entry in MANIFEST["claims"] + MANIFEST["external_citations"]:
        for p in entry["printed"]:
            p = p.strip()
            forms |= {p, p.lstrip("+−-"), p.replace(",", ""),
                      p.rstrip("%x×").rstrip(" ms").strip()}
    for d in MANIFEST["drift"]:
        for p in d["printed"]:
            forms |= {p.strip(), p.replace(",", "")}
    # A non-metric may narrow itself to the lines it applies to. Ignoring that
    # `context` would let a broad pattern silently swallow real claims - which is
    # exactly what a mutation caught when this check first ran.
    rules = []
    for n in MANIFEST["non_metrics"]:
        match = ((lambda t, lit=n["literal"]: t == lit) if "literal" in n
                 else (lambda t, rx=re.compile(n["pattern"]): bool(rx.match(t))))
        ctx = re.compile(n["context"]) if n.get("context") else None
        rules.append((match, ctx))
    return forms, rules


def test_every_printed_number_is_accounted_for() -> None:
    print("\n- 100% of printed numbers resolve to evidence -")
    forms, rules = _accounted_forms()
    total = accounted = 0
    for doc in MANIFEST["scope"]["docs"]:
        text = FENCE.sub("", (ROOT / doc).read_text(encoding="utf-8"))
        lines = text.splitlines()
        orphans: dict[str, list[int]] = {}
        for m in NUMBER.finditer(text):
            token = m.group(0)
            total += 1
            lineno = text[:m.start()].count("\n") + 1
            line = lines[lineno - 1] if lineno <= len(lines) else ""
            if (token in forms or token.replace(",", "") in forms
                    or any(match(token) and (ctx is None or ctx.search(line))
                           for match, ctx in rules)):
                accounted += 1
                continue
            orphans.setdefault(token, []).append(lineno)
        detail = "; ".join(f"{t} (line {ls[0]})" for t, ls in
                           sorted(orphans.items())[:6])
        check(f"{doc}: every printed number is accounted for", not orphans, detail)
    check(f"overall coverage is 100% ({accounted}/{total})", accounted == total,
          f"{accounted}/{total}")


def _tracked_markdown() -> list[str] | None:
    """Every tracked .md, from git. None when git is unavailable.

    Globbing is not an option: research/embed_universal/data/ vendors thousands of
    third-party markdown files that git correctly ignores.
    """
    try:
        out = subprocess.run(["git", "ls-files", "*.md"], cwd=ROOT,
                             capture_output=True, text=True, timeout=60)
    except (OSError, subprocess.SubprocessError):
        return None
    return sorted(out.stdout.split()) if out.returncode == 0 else None


def _numeric_tokens(doc: str) -> int:
    """Evidence-bearing numeric tokens in a document.

    Tokens matched by a context-free non-metric rule - a year, a month, a Python
    version, a bare single digit - are excluded. Otherwise dating a comparative claim
    ("measured 2026-07-05") would count as *adding* unevidenced numbers and trip the
    ratchet, punishing exactly the change task B3 asks for.
    """
    text = (ROOT / doc).read_text(encoding="utf-8", errors="replace")
    # Numbers inside a generated region are produced from committed data by a tool
    # whose own check runs in CI. They are the opposite of unregistered, so counting
    # them would make generating a table look like adding unevidenced claims.
    text = GENERATED_REGION.sub("", text)
    text = FENCE.sub("", text)
    ignore = [re.compile(n["pattern"]) for n in MANIFEST["non_metrics"]
              if "pattern" in n and not n.get("context")]
    literals = {n["literal"] for n in MANIFEST["non_metrics"]
                if "literal" in n and not n.get("context")}
    return sum(1 for t in NUMBER.findall(text)
               if t not in literals and not any(rx.match(t) for rx in ignore))


def test_document_register_covers_every_tracked_markdown() -> None:
    print("\n- every tracked document has a governance mode -")
    tracked = _tracked_markdown()
    if tracked is None:
        print("       (git unavailable - register coverage not checked)")
        return

    register = MANIFEST["documents"]
    unregistered = [d for d in tracked if d not in register]
    check("no tracked document is missing from the register", not unregistered,
          ", ".join(unregistered[:5]))

    stale = [d for d in register if d not in tracked]
    check("the register names no document that no longer exists", not stale,
          ", ".join(stale[:5]))

    modes = {"governed", "exempt", "backlog"}
    bad = [d for d, e in register.items() if e.get("governance") not in modes]
    check("every entry declares a known governance mode", not bad, ", ".join(bad[:5]))

    silent = [d for d, e in register.items()
              if e["governance"] == "exempt" and not e.get("reason")]
    check("every exemption states its reason", not silent, ", ".join(silent[:5]))

    governed = sorted(d for d, e in register.items() if e["governance"] == "governed")
    check("the governed set is exactly the manifest's declared scope",
          governed == sorted(MANIFEST["scope"]["docs"]),
          f"{governed} vs {sorted(MANIFEST['scope']['docs'])}")


def test_the_backlog_can_only_shrink() -> None:
    """A ratchet. Registering a document's numbers is work no task currently owns, so
    the contract that matters today is that the unregistered surface never grows."""
    print("\n- the unregistered surface never grows -")
    grown, shrunk = [], []
    for doc, entry in MANIFEST["documents"].items():
        if entry["governance"] != "backlog":
            continue
        actual = _numeric_tokens(doc)
        if actual > entry["budget"]:
            grown.append(f"{doc}: {actual} > budget {entry['budget']}")
        elif actual < entry["budget"]:
            shrunk.append(f"{doc}: {actual} < budget {entry['budget']}")
    check("no backlog document prints more numbers than its budget", not grown,
          "; ".join(grown[:4]))
    check("no budget is stale (lower it when a document shrinks)", not shrunk,
          "; ".join(shrunk[:4]))
    total = sum(e["budget"] for e in MANIFEST["documents"].values()
                if e["governance"] == "backlog")
    print(f"       ({total} numbers across "
          f"{sum(1 for e in MANIFEST['documents'].values() if e['governance'] == 'backlog')}"
          f" documents remain unregistered)")


def test_generated_regions_match_the_manifest() -> None:
    print("\n- the generated tables are current -")
    proc = subprocess.run([sys.executable, str(ROOT / "tools" / "render_claims.py")],
                          cwd=ROOT, capture_output=True, text=True, timeout=300)
    check("tools/render_claims.py reports every region current",
          proc.returncode == 0,
          (proc.stdout + proc.stderr).strip().replace("\n", " | ")[:400])


def test_drift_entries_carry_the_correct_value() -> None:
    print("\n- the drift register is usable -")
    incomplete = [d.get("doc", "?") for d in MANIFEST["drift"]
                  if not (d.get("printed") and d.get("claims")
                          and d.get("correct") and d.get("note"))]
    check("every drift entry names the doc, the claims and the correct value",
          not incomplete, ", ".join(incomplete[:4]))

    scoped = [d["doc"] for d in MANIFEST["drift"]
              if d["doc"] not in MANIFEST["scope"]["docs"]]
    check("drift is only recorded for documents in scope", not scoped,
          ", ".join(scoped))

    still_printed = []
    for d in MANIFEST["drift"]:
        text = FENCE.sub("", (ROOT / d["doc"]).read_text(encoding="utf-8"))
        if not any(p in text for p in d["printed"]):
            still_printed.append(d["doc"])
    check("every drift entry still describes what the document prints",
          not still_printed,
          ", ".join(still_printed) + " (entry is stale - the doc was fixed; "
          "delete the entry)")
    print(f"       ({len(MANIFEST['drift'])} drift entries open - the tables are "
          f"generated, so an entry only opens for a figure a change cannot fix yet)")


if __name__ == "__main__":
    for _name, _fn in sorted(globals().items()):
        if _name.startswith("test_") and callable(_fn):
            try:
                _fn()
            except Exception as exc:            # noqa: BLE001 - report, keep going
                FAILED += 1
                print(f"  ERR  {_name}: {type(exc).__name__}: {exc}")
    print(f"\nevidence manifest: {PASSED} passed, {FAILED} failed")
    raise SystemExit(1 if FAILED else 0)
