#!/usr/bin/env python3
"""PREREG-V3 plan step A3.i: research/v3/d1_tag.py against a fake Ollama on a free port, offline.

The auditor's Q-A3-1 and the A3.i conditions:
* the tag is nvt3-bge-m3-d1, from the committed Modelfile (FROM bge-m3, PARAMETER num_batch 2048 - nothing else),
  bound by its sha256;
* e1: the base must be present at the digest the inventory run recorded - re-read from /api/tags immediately before
  the create (condition 1); absent or moved = refused, no create, no pull;
* e2: the tag must be absent - present = refused, no create (no silent re-create);
* e3: /api/tags after the create differs from before by exactly one new line, the tag - anything else changed or
  removed is a named problem;
* /api/show confirms num_batch 2048 and the base's model layer (the same FROM blob);
* /api/ps before and after: the loaded set is unchanged (condition 3) - a create that loads a model is named;
* the tag's digest goes to the record (FREEZE-V3), and verify_tag() is what every embedding stand calls before its
  first embed (condition 2): a missing or moved tag is a problem, never a re-create;
* only GET /api/version, /api/tags, /api/ps and POST /api/create, /api/show on 127.0.0.1 - anything else is refused
  before a byte is sent.

    python tests/_test_v3_d1_tag.py
"""
from __future__ import annotations

import hashlib
import importlib.util
import json
import shutil
import sys
import tempfile
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))

import _env_guard  # noqa: F401,E402  hermetic like every suite


def _load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


D = _load("v3_d1_tag", ROOT / "research" / "v3" / "d1_tag.py")
PASSED = FAILED = 0


def check(name: str, cond: bool, detail: str = "") -> None:
    global PASSED, FAILED
    if cond:
        PASSED += 1
        print(f"  ok   {name}")
    else:
        FAILED += 1
        print(f"  FAIL {name}" + (f" - {detail}" if detail else ""))


def refused(fn, words: str = "") -> bool:
    try:
        fn()
    except D.TagRefused as e:
        return words in str(e)
    except Exception:  # noqa: BLE001
        return False
    return False


BASE_DIGEST = "3" * 64
BLOB = "sha256-" + "a" * 64


#: The real /api/show key set of bge-m3:latest on Ollama 0.34.4 (the auditor's read-only measurement, 2026-09-27):
#: capabilities, details, license, model_info, modelfile, modified_at, template - and NO "parameters".
REAL_BASE_SHOW = {"capabilities": ["embedding"], "details": {"family": "bert"}, "license": "MIT",
                  "model_info": {"general.architecture": "bert"},
                  "modelfile": f"# Modelfile generated by \"ollama show\"\nFROM C:\\Users\\x\\.ollama\\models\\blobs\\{BLOB}\n",
                  "modified_at": "2026-09-01T00:00:00Z", "template": "{{ .Prompt }}"}


def model(name: str, digest: str, modified: str = "2026-09-01T00:00:00Z") -> dict:
    return {"name": name, "model": name, "digest": digest, "size": 1, "modified_at": modified}


class Fake:
    """A stateful fake Ollama. ``mode`` bends one behaviour per test."""

    def __init__(self, mode: str = "ok", version: str = "0.12.3") -> None:
        self.mode, self.version, self.seen, self.bodies, self.shows = mode, version, [], [], []
        self.models = [model("bge-m3:latest", BASE_DIGEST), model("qwen3.6:27b", "a50eda8ed977" + "0" * 52),
                       model("owner-private:7b", "4" * 64)]
        self.loaded = [{"name": "qwen3.6:27b"}]
        self.tags_reads = 0
        if mode == "tag_present":
            self.models.append(model(D.TAG + ":latest", "5" * 64))
        if mode == "base_absent":
            self.models = [m for m in self.models if not m["name"].startswith("bge-m3")]

    def tags(self) -> dict:
        self.tags_reads += 1
        if self.mode == "base_moves" and self.tags_reads >= 2:      # after the inventory run, before the create
            for m in self.models:
                if m["name"] == "bge-m3:latest":
                    m["digest"] = "9" * 64
        return {"models": [dict(m) for m in self.models]}

    def create(self, body: dict) -> dict:
        self.bodies.append(body)
        self.models.append(model(D.TAG + ":latest", "6" * 64, "2026-09-26T23:59:00Z"))
        if self.mode == "create_touches_other":
            self.models[1]["modified_at"] = "2026-09-26T23:59:00Z"
        if self.mode == "create_removes_other":
            self.models = [m for m in self.models if m["name"] != "owner-private:7b"]
        if self.mode == "create_adds_extra":
            self.models.append(model("stray:1b", "c" * 64))
        if self.mode == "create_loads":
            self.loaded.append({"name": "bge-m3:latest"})
        return {"status": "success"}

    def show(self, body: dict) -> dict:
        name = body.get("model") or body.get("name")
        tag = name.startswith(D.TAG)
        self.shows.append((name, bool(self.bodies)))
        if self.mode == "base_no_from" and not tag:
            return {"modelfile": "# Modelfile\n# no FROM line\n", "parameters": ""}
        if self.mode == "base_bad_params" and not tag:
            return {**REAL_BASE_SHOW, "parameters": "a line that is not name-value\nnum_batch"}
        if self.mode == "no_from_after" and self.bodies:
            return {"modelfile": "# Modelfile\n", "parameters": "num_batch 2048"} if tag else {"modelfile": "# Modelfile\n"}
        if not tag:
            return dict(REAL_BASE_SHOW)                    # the real bge-m3 on 0.34.4: no "parameters" key at all
        blob = BLOB if self.mode != "other_blob" else "sha256-" + "b" * 64
        out = {"modelfile": f"# Modelfile generated\nFROM C:\\Users\\x\\.ollama\\models\\blobs\\{blob}\n",
               "parameters": "num_batch                      2048" if self.mode != "no_param" else ""}
        if self.mode == "tag_no_params":
            del out["parameters"]
        return out


def serve(fake: Fake):
    class H(BaseHTTPRequestHandler):
        def log_message(self, *a):
            pass

        def _send(self, obj):
            data = json.dumps(obj).encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(data)))
            self.end_headers()
            self.wfile.write(data)

        def do_GET(self):
            fake.seen.append(("GET", self.path))
            if self.path == "/api/version":
                self._send({"version": fake.version})
            elif self.path == "/api/tags":
                self._send(fake.tags())
            elif self.path == "/api/ps":
                self._send({"models": list(fake.loaded)})
            else:
                self._send({})

        def do_POST(self):
            fake.seen.append(("POST", self.path))
            body = json.loads(self.rfile.read(int(self.headers.get("Content-Length") or 0)) or b"{}")
            self._send(fake.create(body) if self.path == "/api/create" else fake.show(body) if self.path == "/api/show" else {})

    srv = ThreadingHTTPServer(("127.0.0.1", 0), H)
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    return srv


TMP = Path(tempfile.mkdtemp(prefix="nvt3_d1tag_"))


def inventory(tag: str, *, digest: str = BASE_DIGEST, version: str = "0.12.3", problems: list | None = None) -> Path:
    """An A3.h inventory record as ollama_inventory writes it (only the fields d1_tag reads)."""
    d = TMP / tag / "_inventory" / "ollama" / "o1"
    d.mkdir(parents=True)
    rec = {"run": "o1", "version": version, "problems": problems or [],
           "pins": {"bge-m3": {"present": True, "found": "bge-m3:latest", "digest": digest, "digest12": digest[:12]}}}
    (d / "record.json").write_bytes(json.dumps(rec).encode())
    return d / "record.json"


def run(tag: str, mode: str = "ok", **inv) -> tuple[dict, Fake]:
    fake = Fake(mode)
    srv = serve(fake)
    try:
        rec = D.run_create(TMP / tag / "runs", run="d1", inventory=inventory(tag, **inv), port=srv.server_address[1])
    finally:
        srv.shutdown()
    return rec, fake


print("\n- the requests and the Modelfile -")
check("the tool may ask only GET /api/version, /api/tags, /api/ps and POST /api/create, /api/show, on 127.0.0.1",
      D.ALLOWED == {("GET", "/api/version"), ("GET", "/api/tags"), ("GET", "/api/ps"), ("POST", "/api/create"),
                    ("POST", "/api/show")} and D.HOST == "127.0.0.1")
for label, (method, path, host) in (("a DELETE", ("DELETE", "/api/delete", "127.0.0.1")),
                                    ("a pull", ("POST", "/api/pull", "127.0.0.1")),
                                    ("an embed", ("POST", "/api/embed", "127.0.0.1")),
                                    ("another host", ("GET", "/api/tags", "localhost"))):
    check(f"{label} is refused before a byte is sent", refused(lambda m=method, p=path, h=host: D.request(m, p, host=h, port=1), "refused"))
mf = (ROOT / "research" / "v3" / "d1_tag.Modelfile").read_bytes()
check("the committed Modelfile is FROM bge-m3 and PARAMETER num_batch 2048 only, LF, bound by its sha256",
      mf == b"FROM bge-m3\nPARAMETER num_batch 2048\n" and hashlib.sha256(mf).hexdigest() == D.MODELFILE_SHA256)
check("the Modelfile parses to the base and the one D1 option", D.parse_modelfile(mf.decode()) == ("bge-m3", {"num_batch": 2048}))
for label, text in (("another option", "FROM bge-m3\nPARAMETER num_batch 2048\nPARAMETER num_ctx 8192\n"),
                    ("another base", "FROM nomic-embed-text\nPARAMETER num_batch 2048\n"),
                    ("a template line", "FROM bge-m3\nPARAMETER num_batch 2048\nTEMPLATE x\n")):
    check(f"a Modelfile with {label} is refused", refused(lambda t=text: D.parse_modelfile(t), "Modelfile"))
check("the create body follows the recorded Ollama version: {model, from, parameters} from 0.6 on",
      D.create_body("0.12.3", "bge-m3:latest", {"num_batch": 2048})
      == {"model": D.TAG, "from": "bge-m3:latest", "parameters": {"num_batch": 2048}, "stream": False})
check("... the legacy {name, modelfile} before 0.5",
      D.create_body("0.4.7", "bge-m3:latest", {"num_batch": 2048})
      == {"name": D.TAG, "modelfile": "FROM bge-m3:latest\nPARAMETER num_batch 2048\n", "stream": False})
check("... and an unknown or in-between version is refused, never guessed",
      refused(lambda: D.create_body("0.5.3", "bge-m3:latest", {"num_batch": 2048}), "version")
      and refused(lambda: D.create_body("dev", "bge-m3:latest", {"num_batch": 2048}), "version"))

print("\n- a clean create -")
rec, fake = run("ok")
check("created: no problem, the tag's digest recorded, the base's digest recorded",
      rec["problems"] == [] and rec.get("tag") == {"name": D.TAG + ":latest", "digest": "6" * 64}
      and rec.get("base") == {"name": "bge-m3:latest", "digest": BASE_DIGEST}, str(rec))
check("one create, with the new-form body, and nothing else written",
      fake.bodies == [{"model": D.TAG, "from": "bge-m3:latest", "parameters": {"num_batch": 2048}, "stream": False}]
      and [s for s in fake.seen if s[0] == "POST"].count(("POST", "/api/create")) == 1, str(fake.bodies))
check("the request right before the create is a fresh /api/tags read (condition 1); /api/ps before and after",
      ("POST", "/api/create") in fake.seen and fake.seen[fake.seen.index(("POST", "/api/create")) - 1] == ("GET", "/api/tags")
      and fake.seen.count(("GET", "/api/ps")) == 2, str(fake.seen))
check("preflight: the base's /api/show is read BEFORE the create, and recorded by its blob id and parameter names only",
      fake.shows[0] == ("bge-m3:latest", False) and rec.get("preflight") == {"model": "bge-m3:latest", "from_blob": BLOB,
                                                                          "parameter_names": []}
      and "Modelfile generated" not in json.dumps(rec), str((fake.shows, rec.get("preflight"))))
check("a clean create strands nothing", "stranded" not in rec)
check("/api/show confirmed num_batch 2048 and the base's model layer",
      rec.get("show") == {"num_batch": 2048, "same_model_layer": True}, str(rec.get("show")))
check("the loaded set is unchanged (condition 3)", rec.get("ps") == {"before": ["qwen3.6:27b"], "after": ["qwen3.6:27b"]}, str(rec.get("ps")))
out = TMP / "ok" / "runs" / "_d1tag" / "d1"
check("the record and both full tag lists are kept in the runs tree",
      json.loads((out / "record.json").read_bytes()).get("tag") == rec.get("tag") and (out / "tags_before.json").is_file()
      and (out / "tags_after.json").is_file())
check("the Modelfile's sha256 is in the record", rec["modelfile_sha256"] == D.MODELFILE_SHA256)
check("a used run label is refused", refused(lambda: D.run_create(TMP / "ok" / "runs", run="d1", inventory=inventory("ok2"), port=1),
                                             "used before"))

print("\n- e1, e2: refused before any create -")
for mode, words, label in (("base_absent", "e1", "a base absent from the store"),
                           ("base_moves", "e1", "a base whose digest moved since the inventory (condition 1)"),
                           ("tag_present", "e2", "a tag already present (no silent re-create)")):
    r, f = run(mode, mode)
    check(f"{label}: refused, no create", any(p.startswith(words) for p in r["problems"]) and f.bodies == []
          and "tag" not in r, str(r["problems"]))
check("P3: the real base show (the 7 keys, no parameters) passes the preflight and the create is called",
      sorted(REAL_BASE_SHOW) == ["capabilities", "details", "license", "model_info", "modelfile", "modified_at", "template"]
      and (rec.get("preflight") or {}).get("parameter_names") == [] and len(fake.bodies) == 1, str(rec.get("preflight")))
for mode, label in (("base_no_from", "a base /api/show with no FROM line"),
                    ("base_bad_params", "a base /api/show whose parameters field is present but does not parse")):
    r, f = run(mode, mode)
    check(f"preflight: {label} is refused - create never called, nothing in the store",
          any(p.startswith("preflight:") for p in r["problems"]) and f.bodies == [] and "tag" not in r
          and ("POST", "/api/create") not in f.seen, str(r["problems"]))
r, f = run("inv_bad", problems=["qwen3.6:27b (J1): missing"])
check("an inventory record with problems is not a base - refused, no create",
      any(p.startswith("e1") for p in r["problems"]) and f.bodies == [], str(r["problems"]))
r, f = run("inv_digest", digest="8" * 64)
check("the inventory's digest must be the store's - otherwise refused, no create",
      any(p.startswith("e1") for p in r["problems"]) and f.bodies == [], str(r["problems"]))

r, f = run("inv_version", version="0.11.0")
check("an Ollama version other than the inventory's is refused, no create",
      any(p.startswith("e1: Ollama is") for p in r["problems"]) and f.bodies == [], str(r["problems"]))
_real_mf = D.MODELFILE
D.MODELFILE = TMP / "tampered.Modelfile"
D.MODELFILE.write_bytes(b"FROM bge-m3\nPARAMETER num_batch 4096\n")
try:
    tampered = refused(lambda: run("mf_tampered"), "not the committed one")
finally:
    D.MODELFILE = _real_mf
check("a Modelfile that is not the committed one (by sha256) is refused before any request", tampered)

print("\n- e3 and the checks after the create -")
for mode, words, label in (("create_touches_other", "e3", "another model's line changed"),
                           ("create_adds_extra", "e3", "a second new line beside the tag"),
                           ("create_removes_other", "e3", "another model removed"),
                           ("create_loads", "ps", "the create loaded a model (a woken model without the announcement)"),
                           ("other_blob", "show", "the tag's model layer is not the base's"),
                           ("no_param", "show", "the tag does not carry num_batch 2048"),
                           ("no_from_after", "show", "IB: no FROM on either side after the create is not the same layer"),
                           ("tag_no_params", "show: the tag's /api/show has no parameters field",
                            "P2: a tag show with no parameters field after the create")):
    r, f = run(mode, mode)
    check(f"{label}: a named problem", any(p.startswith(words) for p in r["problems"]), str(r["problems"]))
    check(f"... and the tag is stranded by the rule (it stays; nothing else runs; the owner removes it, recorded)",
          r.get("stranded") == {"tag": D.TAG + ":latest", "rule": D.STRANDED_RULE} and "ollama rm" in D.STRANDED_RULE,
          str(r.get("stranded")))

print("\n- verify_tag(): what every embedding stand calls before its first embed (condition 2) -")
tags_ok = {"models": [model(D.TAG + ":latest", "6" * 64)]}
check("the tag at its recorded digest passes", D.verify_tag(tags_ok, "6" * 64) == [])
check("a missing tag is a problem", D.verify_tag({"models": []}, "6" * 64) != [])
check("a moved tag is a problem", D.verify_tag({"models": [model(D.TAG + ":latest", "7" * 64)]}, "6" * 64) != [])
check("verify_tag never creates: it only reads the tag list it is given", "request" not in D.verify_tag.__code__.co_names)

shutil.rmtree(TMP, ignore_errors=True)
print(f"\nv3 d1 tag: {PASSED} passed, {FAILED} failed")
sys.exit(1 if FAILED else 0)
